export const amenityKeys = [
  "combined-access",
  "dining-indoor-areas",
  "drip-coffee-maker",
  "family-groups",
  "fiber-wifi",
  "free-street-parking",
  "full-bathrooms",
  "full-kitchen",
  "gas-stove-oven",
  "hot-water",
  "independent-bedrooms",
  "refrigerator",
  "bed-linens",
  "portable-fans",
  "safe-box",
  "exercise-equipment",
  "shared-patio",
  "luggage-drop-off",
] as const;

export type BuiltInAmenityKey = (typeof amenityKeys)[number];

// The built-in tuple preserves ordering and seed autocomplete, while runtime
// catalog creation may add additional stable keys generated by the server.
export type AmenityKey = BuiltInAmenityKey | (string & {});

export const amenityIconNames = [
  "bath",
  "bed",
  "briefcase",
  "car",
  "chefHat",
  "coffee",
  "dumbbell",
  "fan",
  "flame",
  "home",
  "refrigerator",
  "showerHead",
  "treePalm",
  "utensils",
  "shieldCheck",
  "wifi",
  "users",
] as const;

export type AmenityIconName = (typeof amenityIconNames)[number];

export type AmenityDefinition = Readonly<{
  key: AmenityKey;
  icon: AmenityIconName;
  label: Readonly<{
    es: string;
    en: string;
  }>;
}>;
