ALTER TYPE "trp_booking"."email_notification_type" ADD VALUE IF NOT EXISTS 'ADMIN_ADDITIONAL_CHARGE_PAYMENT_REQUIRED';
ALTER TYPE "trp_booking"."email_notification_type" ADD VALUE IF NOT EXISTS 'ADDITIONAL_CHARGE_PAYMENT_APPROVED';
ALTER TYPE "trp_booking"."email_notification_type" ADD VALUE IF NOT EXISTS 'ADMIN_ADDITIONAL_CHARGE_PAYMENT_APPROVED';
ALTER TYPE "trp_booking"."email_notification_type" ADD VALUE IF NOT EXISTS 'ADDITIONAL_CHARGE_REFUND_PROCESSED';
ALTER TYPE "trp_booking"."email_notification_type" ADD VALUE IF NOT EXISTS 'ADMIN_ADDITIONAL_CHARGE_REFUND_PROCESSED';
