export const adminReviewCopy = {
  badge: "Fase 9.7",
  title: "Revisión operativa de reservas y pagos.",
  description:
    "Vista mínima para revisar reservas directas, estados de pago y diagnósticos seguros de Tilopay sin agregar acciones que alteren reservas o pagos.",
  sections: {
    stats: "Resumen operativo",
    reservations: "Reservas directas recientes",
    payments: "Pagos recientes",
    clientEvents: "Eventos seguros del cliente Tilopay",
    guardrails: "Límites de 9.7",
  },
  labels: {
    generatedAt: "Datos generados",
    signedInAs: "Sesión iniciada como",
    publicSite: "Ver sitio público",
    signOut: "Cerrar sesión",
    totalReservations: "Reservas",
    totalPayments: "Pagos",
    totalClientEvents: "Eventos SDK",
    statusBreakdown: "Distribución por estado",
    reservation: "Reserva",
    payment: "Pago",
    property: "Alojamiento",
    guest: "Huésped",
    guestEmail: "Correo",
    guestPhone: "Teléfono",
    guestCountry: "País",
    dates: "Fechas",
    guestCount: "Huéspedes",
    total: "Total",
    status: "Estado",
    latestPaymentStatus: "Último pago",
    expiresAt: "Expira",
    confirmedAt: "Confirmada",
    createdAt: "Creada",
    updatedAt: "Actualizada",
    provider: "Proveedor",
    providerReference: "Order number",
    providerTransactionId: "Transacción proveedor",
    paidAt: "Pagado",
    failedAt: "Falló",
    diagnostics: "Diagnóstico seguro",
    providerCode: "Código",
    providerMessage: "Mensaje",
    authorization: "Autorización",
    providerOrder: "Orden",
    tilopayTransaction: "TPT / transacción Tilopay",
    orderHashStatus: "OrderHash / boundary",
    eventType: "Evento",
    environment: "Ambiente",
    locale: "Idioma",
    paymentMethod: "Método",
    cardBrand: "Marca detectada",
    sdkMessage: "Mensaje SDK",
    preflightStatus: "Preflight",
    preflightExpiresAt: "Preflight expira",
    noReservations: "Todavía no hay reservas directas para mostrar.",
    noPayments: "Todavía no hay pagos para mostrar.",
    noClientEvents: "Todavía no hay eventos SDK registrados.",
    unavailable: "No disponible",
  },
  notes: {
    readOnly:
      "Esta vista es solo lectura. No confirma reservas, no cancela reservas, no procesa reembolsos y no modifica calendarios.",
    paymentDrivenConfirmation:
      "La reserva se mantiene payment-driven: solo un pago APPROVED validado server-side puede confirmar una reserva.",
    safeDiagnostics:
      "Los diagnósticos excluyen número de tarjeta, CVV, fecha de expiración y tokenización de tarjeta.",
  },
  guardrails: [
    "No mostrar ni almacenar datos de tarjeta.",
    "No agregar confirmación manual que salte la validación server-side del pago.",
    "No agregar comportamiento PMS ni reemplazar TAMIAS.",
    "No enviar emails de Phase 10 desde esta subfase.",
  ],
} as const;
